### Invocar al servidor en mi maquina: localhost
###Listado de tareas
GET http://localhost:3000/tasks
content-Type: application/json

### Crear una nueva tarea
POST http://localhost:3000/tasks
content-Type: application/json

{
    "title": "Tarea 1",
    "detail": "Detalle de la tarea 1"
}
### Listado de tareas
GET http://localhost:3000/tasks/1
###content-Type: application/json
DELETE http://localhost:3000/tasks/1
###editar tarea

### eliminar tarea
### marcar completo
### marcar pendiente